version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Building the project..."
  build:
    commands:
      - echo "Building the project..."
      - mkdir -p reports
      - pytest --junitxml=reports/results.xml --tb=short
  post_build:
    commands:
      - echo "Post build phase"

artifacts:
  files:
    - "**/*"
  base-directory: .
  discard-paths: yes

reports:
  pytest_reports:
    files:
      - "reports/results.xml"
    file-format: JUNITXML
